name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: fix try
        run: |
          sudo apt-get update
          sudo apt-get -y install podman
          podman build --security-opt seccomp=unconfined .
        
#      - name: docker build
#        id: build
#        uses: docker/build-push-action@v6
